services:
  ubuntu:
    build:
      context: ./ubuntu
      target: ubuntu_base
      args:
        HTTP_USER: ${HTTP_USER:-www}
        APACHE_USER_UID: ${APACHE_USER_UID:-33}
        APACHE_USER_GID: ${APACHE_USER_GID:-33}
    restart: "unless-stopped"
    ports:
      - "${APACHE_PORT}:80"
      - "443:443"
    volumes:
      - "../:/var/www"
      - "./php/90-on-abi.ini:/etc/php/8.2/apache2/conf.d/90-on-abi.ini"
      - "./php/90-on-abi.ini:/etc/php/8.2/cli/conf.d/90-on-abi.ini"
      - "./apache2/apache2.conf:/etc/apache2/apache2.conf"
      - "./apache2/ports.conf:/etc/apache2/ports.conf"
      - "./apache2/000-default.conf:/etc/apache2/sites-enabled/000-default.conf"
      - "./logs/apache2:/var/log/apache2/"
      - "/etc/localtime:/etc/localtime:ro"
      - "./certs/:/etc/certs/"
    links:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    platform: linux/x86_64
    image: "mysql:5.7"
    restart: "unless-stopped"
    command:
      - "--sql_mode=NO_AUTO_CREATE_USER"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_general_ci"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/logs:/var/log/mysql"
      - "./mysql/my.cnf:/etc/mysql/my.cnf"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-application}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
